### ISSUE TITLE
Write tests for the script

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/k.#1]
Write tests that tests whether it returns `bye.`

**Comment by IAmBullsaw** [comment]
There's no need for a larger test-suite here so I made this smaller one which could scale into a more extensive test-suite if need be.

**Comment by shubhodeep9** [comment]
@IAmBullsaw ok, that's great, I will merge the PR.
Well a heads up, I will create another issue to make tests in Python using tox, for travil-ci.
