### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/k.#2]
Explain how it processes the input -> `k.` and returns -> `bye.`

**Comment by mx0c** [comment]
Is this some kind of Joke ? or am i just to dumb to get it lol

**Comment by shubhodeep9** [comment]
@mx0c this is a very **serious** repository, no _jokes_ around here.

**Comment by mx0c** [comment]
I Understand LOL

**Comment by shivankgtm** [comment]
i want to contribute.

**Comment by shubhodeep9** [comment]
@Shivank98 Cool, get it done then.

**Comment by shubhodeep9** [comment]
@Shivank98 check the PR, I have requested some changes.

**Comment by shivankgtm** [comment]
hope this time i got it right.

**Comment by shubhodeep9** [comment]
@Shivank98 well yes its good, but basic guidelines, if I simple guidelines: if you want to change something, then commit in the same branch, it will automatically be appended in the PR. No need to create a different branch and PR.
As this is your first, I will merge the latest one.

**Comment by shubhodeep9** [comment]
@Shivank98 I hope you have learnt something via this simple repository.
Happy hacking !!!

**Comment by shivankgtm** [comment]
I Thank you @shubhodeep9 
thanks for your support. It was my first open source contribuion to other's project.
feeling Happy :)

**Comment by shubhodeep9** [comment]
@Shivank98 Welcome to open-source.
